openapi: 3.0.3
info:
  title: Task Management API
  description: API for managing tasks
  version: 1.0.0
paths:
  /api/tasks:
    get:
      summary: Retrieve all tasks
      description: Retrieves a list of all tasks.
      responses:
        '200':
          description: A list of tasks retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    description:
                      type: string
                    status:
                      type: string
                    due:
                      type: string
                      format: date-time
        '500':
          description: Internal server error.
      tags:
        - task
    put:
      summary: Create a new task
      description: Creates a new task with the provided data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                due:
                  type: string
                  format: date-time
              required:
                - title
                - description
                - status
                - due
      responses:
        '201':
          description: Task created successfully.
        '400':
          description: Invalid task data.
        '500':
          description: Internal server error.
      tags:
        - task

  /api/{id}:
    get:
      summary: Retrieve a task by ID
      description: Retrieves a task by its unique ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the task.
          schema:
            type: string
      responses:
        '200':
          description: Task retrieved successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
                  due:
                    type: string
                    format: date-time
        '404':
          description: Task not found.
        '500':
          description: Internal server error.
      tags:
        - task

    post:
      summary: Update a task by ID
      description: Updates a task by its unique ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the task.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
                due:
                  type: string
                  format: date-time
      responses:
        '200':
          description: Task updated successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string
                  due:
                    type: string
                    format: date-time
        '400':
          description: Invalid task data.
        '404':
          description: Task not found.
        '500':
          description: Internal server error.
      tags:
        - task

    delete:
      summary: Delete a task by ID
      description: Deletes a task by its unique ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the task.
          schema:
            type: string
      responses:
        '200':
          description: Task deleted successfully.
        '404':
          description: Task not found.
        '500':
          description: Internal server error.
      tags:
        - task
